logdir: /data/data/change_detection/models/2012/EPUNet/res34_bce_woedge/
gpus: [0,1]
distributed: true
fp16: false
lrank: 0

# define model
model:
  architecture: EPUnet
  model_scale: 1
  preweightpath: /data/data
  init_params:
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 3
    classes: 1
    activation: sigmoid

tta: False

data:

  tv_path: /data/data/change_detection_whole/2012/256_128/train/train.csv
  # datasets
  train_dataset:
    name: ChangeDataset_label1
    init_params:
      images_dir: /data/data/change_detection_whole/2012/256_128/train/image
      masks_dir: /data/data/change_detection_whole/2012/256_128/train/mask
      transform_name: train_transform_1

  valid_dataset:
    name: ChangeDataset_label1
    init_params:
      images_dir: /data/data/change_detection_whole/2012/256_128/test/image
      masks_dir: /data/data/change_detection_whole/2012/256_128/test/mask
      transform_name: test_transform_1

  test_dataset:
    name: ChangeDataset_label1
    init_params:
      images_dir: /data/data/change_detection_whole/2012/256_128/test/image
      masks_dir: /data/data/change_detection_whole/2012/256_128/test/mask
      transform_name: test_transform_1

  # loaders
  train_dataloader:
    batch_size: 17
    drop_last: true
    pin_memory: true
    num_workers: 0

  valid_dataloader:
    batch_size: 17
    shuffle: false
    drop_last: false
    pin_memory: true
    num_workers: 0

  test_dataloader:
    batch_size: 17
    shuffle: false
    drop_last: false
    pin_memory: false
    num_workers: 0

training:

  losses:
    mask:
      name: BCELoss
      init_params:

  metrics:
    mask:
      - name: IoU
        init_params:

  optimizer:
    name: adamw
    init_params:
      lr: 0.001

  scheduler:
    name: WarmupPolyLR
    init_params:
      epochs: 60

  fit:
    epochs: 40
    accumulation_steps: 4
    verbose: true

  callbacks: []

logging:
  save_top: 10
