logdir: /data/data/semi_compete/models_pseudo/segformer/b0_tmp/
gpus: [0]
distributed: true
fp16: false
lrank: 0

# define model
model:
  architecture: segformer_b0
  model_scale: 1
  preweightpath: /data/data/semi_compete/models/segformer/b0/checkpoints/best.pth
  init_params:
    in_channels: 3
    classes: 14
  auxiliary_head:
    with_auxiliary_head: false

tta: False

data:
  
  # tv_path: /data/data/landset30/Unet_bifpn/new512_128/pixel_ratio_8000.csv
  # datasets
  train_dataset:
    name: SegDataset
    init_params:
      images_csv: /data/data/semi_compete/clip/tmp/trainpath.csv
      transform_name: train_transform_1

  valid_dataset:
    name: SegDataset
    init_params:
      images_csv: /data/data/semi_compete/clip/tmp/valpath.csv
      transform_name: test_transform_1

  test_dataset:
    name: SegDataset
    init_params:
      images_csv: /data/data/semi_compete/clip/tmp/testpath.csv
      transform_name: test_transform_1

  unlabeled_dataset:
    name: SegDataset
    init_params:
      images_csv: /data/data/semi_compete/clip/tmp/pseudo.csv
      transform_name: test_transform_1
      load_mask: false

  pseudo_dataset:
    name: PseudoDataset
    init_params:
      labeled_images_csv: /data/data/semi_compete/clip/tmp/trainpath.csv
      unlabeled_images_csv: /data/data/semi_compete/clip/tmp/pseudo.csv
      pse_masks_dir: /data/data/semi_compete/clip/tmp/pseudo/mask
      transform_name: train_transform_1

  # loaders
  train_dataloader:
    batch_size: 16
    drop_last: true
    pin_memory: true
    num_workers: 0

  valid_dataloader:
    batch_size: 16
    shuffle: false
    drop_last: false
    pin_memory: true
    num_workers: 0

  test_dataloader:
    batch_size: 16
    shuffle: false
    drop_last: false
    pin_memory: false
    num_workers: 0

  unlabeled_dataloader:
    batch_size: 16
    shuffle: false
    drop_last: false
    pin_memory: true
    num_workers: 0

  pseudo_dataloader:
    batch_size: 16
    drop_last: true
    pin_memory: true
    num_workers: 0

training:

  losses:
    mask:
      name: SoftLabelCrossEntropyLoss
      init_params:

  metrics:
    mask:
      - name: MeanIoU
        init_params:

  optimizer:
    name: adamw
    init_params:
      lr: 0.001

  scheduler:
    name: WarmupPolyLR
    init_params:
      epochs: 60

  fit:
    epochs: 40
    accumulation_steps: 4
    verbose: true

  callbacks: []

  runner:
    model_output_keys: mask


logging:
  save_top: 10
