logdir: /data/data/landset30/models_building/Unet/effb3_dicebce/
gpus: [0,1]
distributed: true
fp16: false
lrank: 0

# define model
model:
  architecture: Unet
  model_scale: 1
  preweightpath: /data/data
  init_params:
    encoder_name: efficientnet-b3
    encoder_weights: imagenet
    in_channels: 6
    classes: 1
    activation: sigmoid

tta: False

data:

  tv_path: /data/data/landset30/Unet_bifpn_building/512_128/pixel_ratio_13159.csv
  # datasets
  train_dataset:
    name: SegDataset
    init_params:
      images_dir: /data/data/landset30/Unet_bifpn_building/512_128/train/image
      masks_dir: /data/data/landset30/Unet_bifpn_building/512_128/train/mask
      transform_name: train_transform_1

  valid_dataset:
    name: SegDataset
    init_params:
      images_dir: /data/data/landset30/Unet_bifpn/512_128/test/image
      masks_dir: /data/data/landset30/Unet_bifpn/512_128/test/mask
      transform_name: test_transform_1

  test_dataset:
    name: SegDataset
    init_params:
      images_dir: /data/data/landset30/Unet_bifpn/512_128/test/image
      masks_dir: /data/data/landset30/Unet_bifpn/512_128/test/mask
      transform_name: test_transform_1

  # loaders
  train_dataloader:
    batch_size: 8
    drop_last: true
    pin_memory: true
    num_workers: 0

  valid_dataloader:
    batch_size: 8
    shuffle: false
    drop_last: false
    pin_memory: true
    num_workers: 0

  test_dataloader:
    batch_size: 8
    shuffle: false
    drop_last: false
    pin_memory: false
    num_workers: 0

training:

  losses:
    mask:
      name: BCEDiceLoss
      init_params:

  metrics:
    mask:
      - name: MicroF1
        init_params:

  optimizer:
    name: adamw
    init_params:
      lr: 0.001

  scheduler:
    name: WarmupPolyLR
    init_params:
      epochs: 60

  fit:
    epochs: 40
    accumulation_steps: 4
    verbose: true

  callbacks: []


logging:
  save_top: 10
