logdir: /data/data/landset30/newmodels_building/UnetPlusPlus/effb3_dicebce_pseudo_13161/
gpus: [0,1]
distributed: true
fp16: false
lrank: 0

# define model
model:
  architecture: UnetPlusPlus
  model_scale: 1
  preweightpath: /data/data/landset30/newmodels_building/UnetPlusPlus/effb3_dicebce/checkpoints/k-ep[29]-0.7184.pth
  init_params:
    encoder_name: efficientnet-b3
    encoder_weights: imagenet
    in_channels: 6
    classes: 1
#    activation: sigmoid

tta: False

data:
  # datasets
  train_dataset:
    name: SegDataset_6
    init_params:
      images_dir: /data/data/landset30/Unet_bifpn/new512_128/train/image
      masks_dir: /data/data/landset30/Unet_bifpn/new512_128/train/mask
      ids_csv: /data/data/landset30/Unet_bifpn/new512_128/pixel_ratio_13161.csv
      transform_name: train_transform_1

  valid_dataset:
    name: SegDataset_6
    init_params:
      images_dir: /data/data/landset30/Unet_bifpn/new512_128/test/image
      masks_dir: /data/data/landset30/Unet_bifpn/new512_128/test/mask
      transform_name: test_transform_1

  test_dataset:
    name: SegDataset_6
    init_params:
      images_dir: /data/data/landset30/Unet_bifpn/new512_128/test/image
      masks_dir: /data/data/landset30/Unet_bifpn/new512_128/test/mask
      transform_name: test_transform_1

  pseudo_dataset:
    name: PseudoDataset
    init_params:
      images_dir: /data/data/landset30/Unet_bifpn/new512_128/train/image
      masks_dir: /data/data/landset30/Unet_bifpn/new512_128/train/mask
      pse_images_dir: /data/data/landset30/Unet_bifpn/new512_128/test/image
      pse_masks_dir: /data/data/landset30/Unet_bifpn/new512_128/pseudo/mask
      ids_csv: /data/data/landset30/Unet_bifpn/new512_128/pixel_ratio_13161.csv
      transform_name: train_transform_1

  # loaders
  train_dataloader:
    batch_size: 7
    drop_last: true
    pin_memory: true
    num_workers: 0

  valid_dataloader:
    batch_size: 7
    shuffle: false
    drop_last: false
    pin_memory: true
    num_workers: 0

  test_dataloader:
    batch_size: 7
    shuffle: false
    drop_last: false
    pin_memory: false
    num_workers: 0

  pseudo_dataloader:
    batch_size: 7
    drop_last: true
    pin_memory: true
    num_workers: 0

training:

  losses:
    mask:
      name: DICE_BCE
      init_params:
        ignore_label: 2

  metrics:
    mask:
      - name: MicroF1
        init_params:
          activation: sigmoid

  optimizer:
    name: adamw
    init_params:
      lr: 0.0001

  scheduler:
    name: PolyLR
    init_params:
      epochs: 60

  fit:
    epochs: 40
    accumulation_steps: 4
    verbose: true

  callbacks: []


logging:
  save_top: 10
